<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Admin</title>
        <link rel="stylesheet" href="/front/css/admin_login.css" />
        <script type="text/javascript" src="/front/js/admin_app.js"></script>
    </head>
    <body>
    	<script type="text/javascript">
    		Resources.admin_auth = '/<?=get_admin_name()?>/auth/index/login/';

			$(function(){
				new Views.AdminAuth();
			})
    	</script>
		<div id="auth_container">
			<table>
				<tr>
					<td>E-mail:</td>
					<td><input name="email" type="text" data-submit="email"/></td>
				</tr>
				<tr>
					<td>Passowrd:</td>
					<td><input name="password" type="password" data-submit="password" /></td>
				</tr>
			</table>

			<div>
				<input type="submit" value="Войти">
			</div>
		</div>
    </body>
</html>