<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="/front/css/main.css" />
		<script type="text/javascript" src="/front/js/app.js"></script>
    </head>
    <body>
    <div id="header-1"></div>
    <div id="container-1">
    	<div id="header-2">
    		<div class="items"><a href="#"><?=_t('/main-menu/item/cars')?></a></div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/events')?></a></div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/press-center')?></a></div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/places/')?></a></div>
    		<br class="clr" />
    	</div>
		<?=$this->_getView()?>
    </div>

    <script>
		<?php if (isset($this->front_labels)){?>
			Models.Labels.install(<?=$this->front_labels?>);
		<?php }?>
    </script>

    </body>
</html>