<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="/front/css/main.css" />
		<script type="text/javascript" src="/front/js/app.js"></script>
    </head>
    <body>
    <div id="header-1"></div>
    <div id="container-1">
    	<div id="header-2">
    		<a href="#" id="main-logo"></a>
    		<div class="items-3">
    			<div class="logo-1">
    				<table class="logo-2">
    					<tr>
    						<td class="logo-3">
    							<div><img src="/front/img/demo/small-car.png" /></div>
    						</td>
    						<td class="logo-4"><a href="#">ivorobioff</a></td>
    					</tr>
    				</table>
    			</div>
    		</div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/places/')?></a></div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/press-center')?></a></div>
    		<div class="items"><a href="#"><?=_t('/main-menu/item/events')?></a></div>
    		<div class="items items-2"><a href="#"><?=_t('/main-menu/item/cars')?></a></div>
    		<br class="clr" />
    	</div>
		<?=$this->_getView()?>
    </div>

    <script>
		<?php if (isset($this->front_labels)){?>
			Models.Labels.install(<?=$this->front_labels?>);
		<?php }?>
    </script>

    </body>
</html>