<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="/front/css/admin_main.css" />
		<script type="text/javascript" src="/front/js/admin_app.js"></script>
    </head>
    <body>
		<div id="tp"></div>
		<div id="content">
			<div>
				<div id="header-top">
					<div id="tp-right">
						<b><?=$this->username?>:</b> <a href="/<?=get_admin_name()?>/auth/index/logout/" class="bmw-1">выход</a>
					</div>
					<br class="clr" />
				 </div>

				 <div id="header">
					 <div id="hd-left">Новости</div>
					 <div id="menu">
							 <a href="#" action="deposit">Установить модуль</a>
							 <a href="#" action="withdrawal">Удалить  модуль</a>
					  </div>
					<br class="clr" />
				 </div>
			</div>
			 <div id="left">
				<ul>
					<li class="select">
						<a href="/operations/flow/index">Денежный поток</a>
					</li>
					<li <?=is_location('/operations/planner/index') ? 'class="select"' : '' ?>>
						<a href="/operations/planner/index">Планировщик</a>
					</li>
					<li <?=is_location('/logs/index/index') ? 'class="select"' : '' ?>>
						<a href="/logs/index/index">Логи</a>
					</li>
					<li <?=is_location('/archive/index/index') ? 'class="select"' : '' ?>>
						<a href="/archive/index/index">Архив</a>
					</li>
				</ul>
			</div>
			<div id="right"><?=$this->_getView();?></div>
		<div id="footer">
		   BMWHouse 1.0. All rights reserved. 2012
		</div>
		</div>

    <?=$this->_getView()?>
<?=$this->_html('common/dialog_layout.phtml')?>
<?=$this->_html('common/confirm_dialog.phtml');?>
<?=$this->_html('common/prompt_dialog.phtml');?>
    </body>
</html>