<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="/front/css/jquery-ui.css" />
        <link rel="stylesheet" href="/front/css/jqgrid.css" />
        <link rel="stylesheet" href="/front/css/admin_main.css" />
		<script type="text/javascript" src="/front/js/admin_app.js"></script>
    </head>
    <body>
		<div id="tp"></div>
		<div id="content">
			<div>
				<div id="header-top">
					<div id="tp-left"><a id="logo" href="/<?=get_admin_name()?>/">BMWHouse 1.0</a></div>
					<div id="tp-right">
						<b><?=$this->username?>:</b> <a href="/<?=get_admin_name()?>/auth/index/logout/" class="bmw-1">выход</a>
					</div>
					<br class="clr" />
				 </div>

				 <div id="header">
					 <div id="hd-left"><?=$this->page_title?></div>
					 <div id="menu">
							 <a href="/<?=get_admin_name()?>/modules/index/managment/">Управление модулями</a>
					  </div>
					<br class="clr" />
				 </div>
			</div>
			 <div id="left">
				<ul>

				</ul>
			</div>
			<div id="right"><?=$this->_getView();?></div>
		<div id="footer">
		   BMWHouse 1.0. All rights reserved. 2012
		</div>
		</div>
<?=$this->_html('common/dialog_layout.phtml')?>
<?=$this->_html('common/confirm_dialog.phtml');?>
<?=$this->_html('common/prompt_dialog.phtml');?>
    </body>
</html>