<div class="blocks">

	<div class="bqq-1">
		<div class="bqq-9">
			Добрый день!
		</div>
		<div class="bqq-8">
			<b><span style="color: orangered;">Регистрация</span></b> |
			Войти
		</div>
		<br class="clr" />
	</div>

	<div class="bqq-2">
		<div class="bqq-7">
			<table class="bqq-4">
				<tr>
					<td class="bqq-5">Никнейм:</td>
					<td><input class="input bqq-3" type="text" /></td>
				</tr>
				<tr>
					<td class="bqq-5">E-mail:</td>
					<td><input class="input bqq-3" type="text" /></td>
				</tr>
				<tr>
					<td class="bqq-5">Пароль:</td>
					<td><input class="input bqq-3" type="text" /></td>
				</tr>
				<tr>
					<td class="bqq-5">Подтвердить пароль:</td>
					<td><input class="input bqq-3" type="text" /></td>
				</tr>
			</table>
		</div>
		<div class="bqq-6">
			<button class="button-1 button-2">Продолжить</button> 	<button class="button-1">Отмена</button>
		</div>
	</div>
</div>