<div id="modules-container">
<div id="test-bb-table"></div>
</div>
<script>
Resources.modules_list = '/<?=get_admin_name();?>/modules/index/{method}-modules/',
Resources.pin_module = '/<?=get_admin_name();?>/modules/index/pin/',
Resources.refresh_module = '/<?=get_admin_name();?>/modules/index/refresh/',
Resources.install_module = '/<?=get_admin_name();?>/modules/index/install/',
Resources.uninstall_module = '/<?=get_admin_name();?>/modules/index/uninstall/',

$(function(){
	new Views.Admin.GridModules();
});

</script>

<script type="text/template" id="test-bb-controls-tmp">
<div id="test-bb-controls">
	<table class="bmw-4">
		<tr>
			<td>
				Страницы: {{pages_line}}
			</td>
			<td class="bmw-6">
				Всего: <b>{{total}}</b> на странице показано:
				<select name="rows_per_page">
					<option value="10" {{on_page 10}}>10</option>
					<option value="20" {{on_page 20}}>20</option>
					<option value="50" {{on_page 50}}>50</option>
					<option value="100" {{on_page 100}}>100</option>
				</select>
			</td>
		</tr>
	</table>
</div>
</script>