var Helpers = {Abstract: {}, Admin:{}};
var Views = {Abstract: {}, Collection: {}, Admin: {}};
var Collections = {Abstract: {}, Admin: {}};
var Models = {Abstract: {}, Admin: {}};
var Routers = {Abstract: {}, Admin: {}};
var Lib = {Abstract: {}, Admin: {}};
var Resources = {};
var DataSource = {};
var Settings = {};